name: Validate Observability Configurations

# This workflow ensures that all Prometheus, Alertmanager, Grafana, and Fluent Bit
# configuration files are syntactically correct before they are merged into the main branch.
# It acts as a critical quality gate for the "Observability as Code" repository.
# It is triggered on pull requests to 'main' and direct pushes to 'main'.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Configs
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up validation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip npm

      - name: 3. Install YAML Linter
        run: pip3 install yamllint

      - name: 4. Install JSON Linter
        run: sudo npm install -g jsonlint

      - name: 5. Install Prometheus Tools (promtool)
        env:
          PROMETHEUS_VERSION: "2.53.0" # Pinning version for consistent validation
        run: |
          echo "Downloading Prometheus v${PROMETHEUS_VERSION}..."
          wget "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz"
          
          echo "Extracting promtool..."
          tar xvfz "prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz"
          
          echo "Moving promtool to /usr/local/bin..."
          sudo mv "prometheus-${PROMETHEUS_VERSION}.linux-amd64/promtool" /usr/local/bin/
          
          echo "Verifying promtool installation..."
          promtool --version

      - name: 6. Install Fluent Bit
        env:
          FLUENTBIT_VERSION: "3.0.4" # Pinning version for consistent validation
        run: |
          echo "Downloading Fluent Bit v${FLUENTBIT_VERSION}..."
          wget "https://github.com/fluent/fluent-bit/archive/refs/tags/v${FLUENTBIT_VERSION}.tar.gz"
          
          echo "Extracting Fluent Bit source..."
          tar xvfz "v${FLUENTBIT_VERSION}.tar.gz"
          
          echo "Building Fluent Bit from source..."
          cd "fluent-bit-${FLUENTBIT_VERSION}/build/"
          cmake .. -DFLB_DEV=On -DFLB_TESTS=Off
          make
          
          echo "Moving fluent-bit to /usr/local/bin..."
          sudo mv bin/fluent-bit /usr/local/bin/
          
          echo "Verifying Fluent Bit installation..."
          fluent-bit --version

      - name: 7. Make validation script executable
        run: chmod +x ./scripts/validate-configs.sh

      - name: 8. Run configuration validation script
        run: ./scripts/validate-configs.sh