.github/workflows/ci.yml
name: TMS Core CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    name: Lint & Test Suite
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: myodoo-password
          POSTGRES_DB: tms_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint with Flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Check import order with isort
        run: |
          isort --check-only .

      - name: Run Tests with Coverage
        env:
          HOST: localhost
          PORT: 5432
          USER: odoo
          PASSWORD: myodoo-password
          DB_NAME: tms_test
        run: |
          pytest --cov=tms_core --cov-report=xml --cov-report=term-missing

      - name: Check Coverage Threshold
        # Fails the build if coverage is below 80% as per REQ-1-504
        run: |
          coverage report --fail-under=80