[tool.black]
line-length = 119
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tms_gps_consumer/tests",
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

# Odoo specific pytest configuration
odoo_test_tags = "tms_gps_consumer"