version: '3.8'

services:
  gps-ingestion-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms-gps-ingestion-service
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/app/src
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: tms-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  rabbitmq_data: